apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::337040981436:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-tFX8CeFYduSb
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::337040981436:user/suresh
      username: suresh
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::337040981436:user/john
      username: john
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::337040981436:user/rahim
      username: rahim
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::337040981436:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-18T05:01:44Z"
  name: aws-auth
  namespace: kube-system
  uid: b7b19e40-dcf1-4c76-a8ae-dfd75a408596
